# Generated by Django 4.2.6 on 2023-11-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_remove_product_pic_remove_upload_desc_upload_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(related_name='product_with_images', to='upload.upload')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_with_images_upload', to='upload.product')),
            ],
        ),
    ]
