# Generated by Django 4.2.7 on 2023-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_productwithimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='our new product is good'),
        ),
    ]
