# Generated by Django 4.2.7 on 2023-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Promoted', 'Promoted')], default='Trending', max_length=12),
            preserve_default=False,
        ),
    ]
